### ISSUE TITLE
Release to conda-forge

### ISSUE THREAD

**Issue by pipinet** [IntelLabs/scenario_execution#102]
[pixi tool](https://pixi.sh) can help developers quickly build ROS2 development environments

this tool package can find in  [conda-forge](https://conda-forge.org/packages)

**Comment by fmirus** [comment]
The core package of scenario execution is available as [pip package](https://pypi.org/project/scenario-execution/), which can be used to install it inside a conda environment (see our [installation instructions](https://intellabs.github.io/scenario_execution/setup.html#installation-with-pip-as-standalone-python-package) for scenario execution as standalone Python package). We are currently not planning to release scenario execution additionally to conda forge.
